source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "2.5.1"

gem "rails", "~> 5.2.1"

gem "active_model_serializers"
gem "aws-sdk-s3", require: false
gem "bootsnap", ">= 1.1.0", require: false
gem "committee", github: "FiNCDeveloper/committee"
gem "counter_culture"
gem "jwt"
gem "kaminari"
gem "newrelic_rpm"
gem "omniauth-github"
gem "pg", ">= 0.18", "< 2.0"
gem "puma", "~> 3.11"
gem "pundit"
gem "rack-cors"
gem "rails-i18n"
gem "redcarpet"
gem "seed-fu"
gem "sentry-raven"
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :development, :test do
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "pry-rails"
  gem "rspec-rails"
end

group :development do
  gem "annotate"
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "onkcop", require: false
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

group :test do
  gem "rspec_junit_formatter"
end

group :doc do
  gem "json_refs", require: false
end
